# Generated by Django 4.2.7 on 2025-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Titulos', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição de Titulos', max_length=70)),
            ],
        ),
    ]
